
<template>
	<div>
		<p class="fileStyle">Music of the Virgin Islands
	The music of the Virgin Islands reflects long-standing cultural ties to the island nations to the south as well as to various European colonialists. Though the United States Virgin Islands and British Virgin Islands are politically separate, they maintain close cultural ties. From its neighbors, the Virgin Islands has imported various pan-Caribbean genres of music, including calypso from Trinidad and reggae from Jamaica.
	The major indigenous form of music is the scratch band (also called fungi band), which use improvised instruments like gourds and washboards to make a kind of music called quelbe. A Virgin Island folk song called cariso is also popular, as well as St. Thomas' bamboula. The quadrille is the traditional folk dance of the islands, and include varieties like St. Croix's Imperial Quadrille and St. Thomas' Flat German Quadrille. The Heritage Dancers are a respected dance troupe that perform traditional folk dances from the Virgin Islands and beyond.
	=== Characteristics
	Virgin Islander culture is syncretic, based primarily on African and European cultures. Though the Danish controlled the present-day U.S. Virgin Islands for many years, the dominant language has been an English-based Creole since the 19th century, and the islands remain much more receptive to English language popular culture than any other. The Dutch, the French and the Danish also contributed elements to the island's culture, as have immigrants from the Arab world, India and other Caribbean islands. The single largest influence on modern Virgin Islander culture, however, comes from the Africans enslaved to work in canefields from the 17th to the mid-19th century. These African slaves brought with them traditions from across a wide swathe of Africa, including what is now Nigeria, Senegal, both Congos, Gambia and Ghana.
	=== Folk music
	Virgin Islander folk music has declined since the mid-20th century, though some traditions, such as scratch bands, remain vibrant. Trends that contributed to this change include the rise of the tourism industry, the switch of American tourists from Cuba to the Virgin Islands following the 1959 revolution, and the growth of industries based on mass radio, television and recorded music. These changes "(diluted) local traditions and (diverted) younger generations" from becoming involved in folk music, because popular styles came to be viewed as having more prestige, class and income.
	=== Scratch bands and fungi music
	Scratch bands, also known as fungi bands and formerly string bands, are a distinctive form of folk ensemble; they have survived the decline of other Virgin Islander folk traditions, through adapting to newly imported instrumentation and songs, and becoming a part of a more general revival of interest in folk culture on the islands. The name scratch band may derive from the sound produced by scraping the squash, an instrument similar to the Puerto Rican guiro, but larger, or from the word squash itself, used to refer to the bands first by American visitors and then by locals.
	The traditional scratch band ensemble varied, but always used a percussive instrument, either the squash, tambourine, or a local form of double-headed barrel drum similar to the Dominican tambora, as well as an accordion, cane flute or violin as a melodic instrument. String instruments were also common, including the banjo, ukulele or a six-string guitar. The ass pipe, made out of a car exhaust tube, often provided the bass, and was played similar to the tuba. Since about the 1980s, the instrumentation for scratch bands became more rigid. The alto saxophone became the most common melodic instrument, replaced sometimes by a silver flute. Conga drums, squash, electric guitar or bass guitar, and a steel (a triangle). Banjo or ukulele, keyboard and additional saxophones or other melodic instruments are more rarely found in modern bands.
	The music of scratch bands are a type of folk music that dates back to the days of slavery. The slaves on the islands used found objects to fashion instruments, such as by making strings out of twine salvaged from old sacks. Lyrics traditionally function as oral history, spreading news and gossip. Modern scratch bands play a wide range of dances, including calypsos, boleros, quadrilles, international pop songs, merengues, mazurkas, waltzes, jigs and other styles. They perform at church services, private parties, public festivals, local dances and fars, christenings and weddings, and also perform for tourists. The scratch band tradition remains most vibrant on St. Croix, where the bands Bully & the Kafooners, Stanley & the Ten Sleepless Knights, and Blinky & the Roadmasters are well known. Scratch bands are less common on St. Thomas, and in the British Virgin Islands, though the popular Elmo & the Sparkplugs hail from Tortola.
	=== Quelbe
	Quelbe is a form of topical folk song, and is the official music of the Virgin Islands. Quelbe is commonly performed by scratch bands, Stanley & the Ten Sleepless Nights being the most popular throughout the Virgin Islands, though their folk origin lays in individuals, who sang the songs in informal settings, celebrations and festivals. These songs typically contained sexual innuendos and double entendres, as well as other hidden meanings; common topics included political events, such as a boycott. One example from the early 20th century chastizes a carousel owner for opposing a wage increase:
	I rather walk and drink rum whole night Before me go ride on LaBega Carousel I rather walk, man, and drink rum whole night Before me go ride on LaBega Carousel You no hear what LaBega say "The people no worth more than fifteen cent a day" You no hear what LaBega say, man "The people no worth more than half cent a day"
	=== Other folk styles
	The quadrille is a folk dance that was formerly an important part of Virgin Islands culture; it is now rarely performed, except on St. Croix. There, locals dance the quadrille at public performance venues, such as St. Gerard's Hall, or as educational spectacles for schools, festivals and holidays, or as entertainment for tourists. Educational and entertainment quadrille troops both wear traditionally styled clothing reminiscent of authentic attire.
	The Virgin Islands tea meetings, the David and Goliath play and masquerade jig all probably derive from elsewhere in the Caribbean. The masquerade jig uses elements of theater, dance, music and oratory, and functions as simple entertainment with improvised jigs alternated with humorous monologues. Tea meetings are now only performed as reconstructions in folkloric ensembles; they were evenings of speech-making, feasting and the singing of hymns and parlor songs. The David and Goliath play features music, dance, theater, and dramatic and witty speechs, all based around the biblical plot of David and Goliath.
	The Afro-Virgin Islander bamboula tradition is now only performed in a reconstructed fashion. It was a style of song, drumming and folk dance, performed by two drummers on one drum; one drum used his hands and heel, and the other two sticks. African-styled dance and group song with refrains were a constant part, with verses frequently improvised by a soloist.
	Traditional Virgin Islander folk music festivals were performed until the late 1950s. Masquerading (mas'ing) was an important tradition, and consisted of groups wearing costumes based around a theme, and playing melodies and rhythms that suggest their identity. Instruments included a fife-and-drum ensemble that featured a cane fife, double-headed bass drum (known as keg or boom-boom) and snare drum (known as kettledrum).
	The Virgin Islander cariso tradition is extinct in a true folk context, but remains an important symbol of Crucian culture, and is performed by folkloric ensembles for educational and holiday events. Carisos were still performed as late as the 1990s by several elderly singers, most famously Ethel McIntosh and Leona Watson. Though similar in some ways to quelbe, cariso is more African in its melodic style, frequent sustained syllables and traditional performance context, namely women singing in groups in call-and-response. Carisos, like quelbe, commemorate historical events, and spread news and opinions about important issues. One particularly famous cariso dates to 1848, and documents the emancipation of the slaves; the first segment is the refrain, sung by a chorus, which is followed by a verse performed by a soloist singer:
	Clear the road, all you clear the road, Clear the road, let the slave them pass, We a go for a-we freedom.
	Hardship in the morning, suffering at night. No one ever help us, it is only Father Ryan. They bring we ya from Africa, that we bornin' land; Bring we ya in slavery, in the land of Sant Cruz.
	=== Modern and recently imported styles
	Until the mid-20th century, the Virgin Islands were largely culturally isolated from international popular music. In the 1960s, a growth in tourism caused an influx of immigrants to fill the service positions the tourism industry created. These immigrants brought with them many styles of popular music, which were popularized by the growth of mass media in the islands, including television and radio.
	By the 1980s, Virgin Islands was home to many imported styles, especially reggae, soca, merengue and rock. Jazz, Western classical music and musical theater, along with international pop stars, were common mainstream interests, while the islands' youth formed bands and dance troupes that played styles popular across the Caribbean, such as reggae, steelpan and soca. The large Puerto Rican population in the Virgin Islands kept popular music from Puerto Rico and the Dominican Republic a major part of the Islands' industry.
	=== Calypso
	The first calypso star from the Virgin Islands was Lloyd "Prince" Thomas, who moved to New York City in the mid-1940s and continued performing for some twenty years. Charles Harris, the Mighty Zebra (a well-known Trinidadian calypsonian) influentially performed in the Virgin Islands in the 1950s; he came for the Carnival in 1952, and stayed, playing at the Virgin Isles Hotel with the LaMotta Brothers Band. The LaMotta Band, led by Bill LaMotta, was a very popular group that recorded several albums and backed Mighty Zebra on a 1957 album for RCA Records. The remaining major early calypso band from the Virgin Islands was the Fabulous McClevertys, who toured widely across the East Coast of the United States at the height of the calypso craze in the late 1950s.
	Another popular Virgin Islands calypsonian is Irvin "Brownie" Brown, who has hosted the islands' Carnival and has been a leading singer, radio entertainer, MC and drummer for many years. Originally from St. Thomas, he learned the timbales as a young man, and joined his uncle's hotel band in 1949 or 1950. The band soon began performing in Florida and elsewhere, and Brownie became known as a calypso singer while also learning bongos, congas and a trap set. They recorded for Monogram and then Art Records, with Mighty Panther and the Haitian singer Calypso Mama. Brownie's return to St. Thomas was followed by joining up with Milo & the Kings, a well-known band, for whom he was a percussion for seventeen years, recording a number of albums and touring across North America and the Caribbean. He began working as a DJ for the WSTA radio station in 1966, and continued for more than three decades; he had a regular talk show with calypso performances, The Original Side of Walter and Brownie.
	=== Soca
	The Virgin Islands has been home to a number of well-known soca bands. Among the oldest and most respected are Milo & the Kings, Jam Band(formerly Eddie & the Movements) 20 Times Road March Champions and the Imagination Brass. More recent popular bands include VIO International, World Famous Xpress Band (St Croix Festival's 2006-2007 Roadmarch Champions), Starlites, and the Musically Dangerous Xtaushun Band (St Croix Festival two-time Road March Champions)." Recently, the JDPP Jammerz, have rapidly made a name for themselves, even winning the 2007 St. Thomas Carnival Road March with the song "Bunny Train".
	Another largely popular soca band as of the last decade(2001-2007) on St Thomas is the "P'your Passion Band". The original "Jam Band" has also slowed up with the tragic death of the bands main front man "Nick "Daddy" Friday" who died back in 2005.
	Popular Virgin Islands bands to date include De Fabulous Stroka Band, Hyvoltage Band, Code 9, Xpress Band, Jam Band, Jam Tyme, UMB Soldiers, JDPP Jammers, Stylee Band, and the Xtaushun Band.
	The most popular Virgin Islands Band and a band before its time, is Seventeen Plus (17+). With the inception of the "riddim Box", the electronic drum machine, 17+ was one of the first bands in the region to master its use as expressed in Seventeen Plus's New Style. It demonstrated the full use of the electronic keyboard, drum machines, vocals and a bass line working together to set the standard for all bands of the electronic drum machine era.
	=== Reggae
	A reggae scene has been flourishing in the Virgin Islands, especially the island of St. Croix. The Virgin Islands reggae scene has achieved much popularity throughout the Lesser Antilles, Puerto Rico, the United States and Europe. Prominent reggae artists from the Virgin Islands include Pressure, Midnite, Dezarie, Army, Abja, Daga Don, Pressure, De Apostle, Niyorah, Bambu Station, Inner Visions, Sebattical Addah, Eno,Revalation, Iba Wicked, Jah Rubal and many more. The reggae music of St. Croix has a distinct "roots" feeling and is strongly rooted in Rastafari. A prominent reggae label in St. Croix is I Grade Records, who have released countless Midnite releases, two Dezarie albums, two Niyorah albums, Army albums and Abja albums. Bambu Station guitarist Tuff Lion, along with Laurent AlBert and Kenyatta Iyatola of I Grade Records produce many of the tracks.
	St. Croix also boasts a reggae radio station, WSTX 100.3 FM, which features Virgin Islands reggae.
	=== Institutions and festivals
	The two most prominent music institutions in the Virgin Islands are the Island Center (on St Croix) and the Reichold Center (on St Thomas). Both these centers provide a venue for concerts of Western classical music, jazz, musical theater and international pop stars. St. Croix is also home to a public performance venue in St. Gerald's Hall in Frederiksted, where locals dance quadrilles and otherwise perform.
	Traditional Virgin Islander folk music festivals were performed until the late 1950s, and were based around costumed masquerading. With the advent of formal celebrations based around parades and festival village, local folk traditions declined, replaced by pan-Caribbean elements like calypso, moko jumbie stilt dancers and visiting performers from other islands.
	=== Education
	There are Virgin Islander institutions that support and promote the islands' folk heritage. Bradley Christian's St. Croix Heritage Dancers, for example, are folkloric group, one of several quadrille ensembles that offer a "compact, staged rendition" of folk traditions, along with educational narration.
	Music education in the Virgin Islands is primarily based around the Western classical tradition, particularly orchestral and concert band music. Local folk music is also a part of the music curriculum; quadrilles are taught in schools in St. Croix, and Charlotte Amalie High School on St. Thomas is home to a well-known student scratch band.
	=== Historiography and musicology
	There is a paucity of historical documentation and musicological research and analysis of Virgin Islander music. The sound recordist Mary Jane Soule and ethnomusicologist Margot Lieth-Philipp collaborated on an annotated CD, Zoop Zoop Zoop: Traditional Music and Folklore of St. Croix, St. Thomas, and St. John; these liner notes are among the comprehensive descriptions of folk music known. Lieth-Phillipp has also published some other material, on bamboula (which she refers to as a "forgotten" style of Caribbean music) and other topics. The loca and the Smithsonian Institution have also documented some folk traditions, but their research remains largely unpublished. Carmen Nibbs-O'Garra, wife of well-known Antiguan calypsonian Figgy, is the author of In de Calypso Tent, which, though perhaps no longer available, contains information of calypso competitions of St. Thomas and also reproduces the lyrics of popular Virgin Islands calypsos, and historical programs from past calypso tents on the islands.
		</p>
	</div>
</template>

<style>
.fileStyle {
	white-space:pre-wrap;
	font-family: Arial;
	font-size: 14px;
	text-align: justify;
	padding-left: 20px;
	padding-right: 20px;
	line-height: 25px;
}.

span {
	color: red;
	font-size: 15px;
}

.el-tag {
	font-size: 15px;
}
</style>
